# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class OfferData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id_offer: int=None, offer_name: str=None, offer_price: float=None, validity_from: datetime=None, validity_until: datetime=None):  # noqa: E501
        """OfferData - a model defined in Swagger

        :param id_offer: The id_offer of this OfferData.  # noqa: E501
        :type id_offer: int
        :param offer_name: The offer_name of this OfferData.  # noqa: E501
        :type offer_name: str
        :param offer_price: The offer_price of this OfferData.  # noqa: E501
        :type offer_price: float
        :param validity_from: The validity_from of this OfferData.  # noqa: E501
        :type validity_from: datetime
        :param validity_until: The validity_until of this OfferData.  # noqa: E501
        :type validity_until: datetime
        """
        self.swagger_types = {
            'id_offer': int,
            'offer_name': str,
            'offer_price': float,
            'validity_from': datetime,
            'validity_until': datetime
        }

        self.attribute_map = {
            'id_offer': 'id_offer',
            'offer_name': 'offerName',
            'offer_price': 'offerPrice',
            'validity_from': 'validity_from',
            'validity_until': 'validity_until'
        }
        self._id_offer = id_offer
        self._offer_name = offer_name
        self._offer_price = offer_price
        self._validity_from = validity_from
        self._validity_until = validity_until

    @classmethod
    def from_dict(cls, dikt) -> 'OfferData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OfferData of this OfferData.  # noqa: E501
        :rtype: OfferData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id_offer(self) -> int:
        """Gets the id_offer of this OfferData.


        :return: The id_offer of this OfferData.
        :rtype: int
        """
        return self._id_offer

    @id_offer.setter
    def id_offer(self, id_offer: int):
        """Sets the id_offer of this OfferData.


        :param id_offer: The id_offer of this OfferData.
        :type id_offer: int
        """

        self._id_offer = id_offer

    @property
    def offer_name(self) -> str:
        """Gets the offer_name of this OfferData.


        :return: The offer_name of this OfferData.
        :rtype: str
        """
        return self._offer_name

    @offer_name.setter
    def offer_name(self, offer_name: str):
        """Sets the offer_name of this OfferData.


        :param offer_name: The offer_name of this OfferData.
        :type offer_name: str
        """

        self._offer_name = offer_name

    @property
    def offer_price(self) -> float:
        """Gets the offer_price of this OfferData.


        :return: The offer_price of this OfferData.
        :rtype: float
        """
        return self._offer_price

    @offer_price.setter
    def offer_price(self, offer_price: float):
        """Sets the offer_price of this OfferData.


        :param offer_price: The offer_price of this OfferData.
        :type offer_price: float
        """

        self._offer_price = offer_price

    @property
    def validity_from(self) -> datetime:
        """Gets the validity_from of this OfferData.


        :return: The validity_from of this OfferData.
        :rtype: datetime
        """
        return self._validity_from

    @validity_from.setter
    def validity_from(self, validity_from: datetime):
        """Sets the validity_from of this OfferData.


        :param validity_from: The validity_from of this OfferData.
        :type validity_from: datetime
        """

        self._validity_from = validity_from

    @property
    def validity_until(self) -> datetime:
        """Gets the validity_until of this OfferData.


        :return: The validity_until of this OfferData.
        :rtype: datetime
        """
        return self._validity_until

    @validity_until.setter
    def validity_until(self, validity_until: datetime):
        """Sets the validity_until of this OfferData.


        :param validity_until: The validity_until of this OfferData.
        :type validity_until: datetime
        """

        self._validity_until = validity_until
