# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RequestGetSingleOffer(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, channel: str=None, external_transaction_id: str=None, id_offer: int=None):  # noqa: E501
        """RequestGetSingleOffer - a model defined in Swagger

        :param channel: The channel of this RequestGetSingleOffer.  # noqa: E501
        :type channel: str
        :param external_transaction_id: The external_transaction_id of this RequestGetSingleOffer.  # noqa: E501
        :type external_transaction_id: str
        :param id_offer: The id_offer of this RequestGetSingleOffer.  # noqa: E501
        :type id_offer: int
        """
        self.swagger_types = {
            'channel': str,
            'external_transaction_id': str,
            'id_offer': int
        }

        self.attribute_map = {
            'channel': 'channel',
            'external_transaction_id': 'externalTransactionId',
            'id_offer': 'id_offer'
        }
        self._channel = channel
        self._external_transaction_id = external_transaction_id
        self._id_offer = id_offer

    @classmethod
    def from_dict(cls, dikt) -> 'RequestGetSingleOffer':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestGetSingleOffer of this RequestGetSingleOffer.  # noqa: E501
        :rtype: RequestGetSingleOffer
        """
        return util.deserialize_model(dikt, cls)

    @property
    def channel(self) -> str:
        """Gets the channel of this RequestGetSingleOffer.


        :return: The channel of this RequestGetSingleOffer.
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel: str):
        """Sets the channel of this RequestGetSingleOffer.


        :param channel: The channel of this RequestGetSingleOffer.
        :type channel: str
        """

        self._channel = channel

    @property
    def external_transaction_id(self) -> str:
        """Gets the external_transaction_id of this RequestGetSingleOffer.


        :return: The external_transaction_id of this RequestGetSingleOffer.
        :rtype: str
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: str):
        """Sets the external_transaction_id of this RequestGetSingleOffer.


        :param external_transaction_id: The external_transaction_id of this RequestGetSingleOffer.
        :type external_transaction_id: str
        """

        self._external_transaction_id = external_transaction_id

    @property
    def id_offer(self) -> int:
        """Gets the id_offer of this RequestGetSingleOffer.


        :return: The id_offer of this RequestGetSingleOffer.
        :rtype: int
        """
        return self._id_offer

    @id_offer.setter
    def id_offer(self, id_offer: int):
        """Sets the id_offer of this RequestGetSingleOffer.


        :param id_offer: The id_offer of this RequestGetSingleOffer.
        :type id_offer: int
        """

        self._id_offer = id_offer
