# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RequestOfferData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id_offer: int=None, offerName: str=None, offerPrice: float=None, validity_from: str=None, validity_until: str=None):  # noqa: E501
        """RequestOfferData - a model defined in Swagger

        :param id_offer: The id_offer of this RequestOfferData.  # noqa: E501
        :type id_offer: int
        :param offerName: The offerName of this RequestOfferData.  # noqa: E501
        :type offerName: str
        :param offerPrice: The offerPrice of this RequestOfferData.  # noqa: E501
        :type offerPrice: float
        :param validity_from: The validity_from of this RequestOfferData.  # noqa: E501
        :type validity_from: datetime
        :param validity_until: The validity_until of this RequestOfferData.  # noqa: E501
        :type validity_until: datetime
        """
        self.swagger_types = {
            'id_offer': int,
            'offerName': str,
            'offerPrice': float,
            'validity_from': str,
            'validity_until': str
        }

        self.attribute_map = {
            'id_offer': 'id_offer',
            'offerName': 'offerName',
            'offerPrice': 'offerPrice',
            'validity_from': 'validity_from',
            'validity_until': 'validity_until'
        }
        self._id_offer = id_offer
        self._offer_name = offerName
        self._offer_price = offerPrice
        self._validity_from = validity_from
        self._validity_until = validity_until

    @classmethod
    def from_dict(cls, dikt) -> 'RequestOfferData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestOfferData of this RequestOfferData.  # noqa: E501
        :rtype: RequestOfferData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id_offer(self) -> int:
        """Gets the id_offer of this RequestOfferData.


        :return: The id_offer of this RequestOfferData.
        :rtype: int
        """
        return self._id_offer

    @id_offer.setter
    def id_offer(self, id_offer: int):
        """Sets the id_offer of this RequestOfferData.


        :param id_offer: The id_offer of this RequestOfferData.
        :type id_offer: int
        """

        self._id_offer = id_offer

    @property
    def offerName(self) -> str:
        """Gets the offerName of this RequestOfferData.


        :return: The offerName of this RequestOfferData.
        :rtype: str
        """
        return self._offer_name

    @offerName.setter
    def offerName(self, offerName: str):
        """Sets the offerName of this RequestOfferData.


        :param offerName: The offerName of this RequestOfferData.
        :type offerName: str
        """

        self._offer_name = offerName

    @property
    def offerPrice(self) -> float:
        """Gets the offerPrice of this RequestOfferData.


        :return: The offerPrice of this RequestOfferData.
        :rtype: float
        """
        return self._offer_price

    @offerPrice.setter
    def offerPrice(self, offerPrice: float):
        """Sets the offerPrice of this RequestOfferData.


        :param offerPrice: The offerPrice of this RequestOfferData.
        :type offerPrice: float
        """

        self._offer_price = offerPrice

    @property
    def validity_from(self) -> str:
        """Gets the validity_from of this RequestOfferData.


        :return: The validity_from of this RequestOfferData.
        :rtype: datetime
        """
        return self._validity_from

    @validity_from.setter
    def validity_from(self, validity_from: str):
        """Sets the validity_from of this RequestOfferData.


        :param validity_from: The validity_from of this RequestOfferData.
        :type validity_from: datetime
        """

        self._validity_from = validity_from

    @property
    def validity_until(self) -> str:
        """Gets the validity_until of this RequestOfferData.


        :return: The validity_until of this RequestOfferData.
        :rtype: datetime
        """
        return self._validity_until

    @validity_until.setter
    def validity_until(self, validity_until: datetime):
        """Sets the validity_until of this RequestOfferData.


        :param validity_until: The validity_until of this RequestOfferData.
        :type validity_until: datetime
        """

        self._validity_until = validity_until
